FROM microsoft/aspnetcore-build AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# build runtime image
FROM microsoft/aspnetcore
RUN apt-get update && apt-get install -y nginx &&  DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "dbmq.dll"]
