
ALTER AVAILABILITY GROUP [AG1]  
 MODIFY REPLICA ON  
N'sqlnode1' WITH   
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://sqlnode1:1433'));  

ALTER AVAILABILITY GROUP [AG1]  
 MODIFY REPLICA ON  
N'sqlnode2' WITH   
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://sqlnode2:1433'));  

ALTER AVAILABILITY GROUP [AG1]  
 MODIFY REPLICA ON  
N'sqlnode3' WITH   
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://sqlnode3:1433'));  

ALTER AVAILABILITY GROUP [AG1]   
MODIFY REPLICA ON  
N'sqlnode1' WITH   
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('sqlnode3','sqlnode2','sqlnode1')));  

ALTER AVAILABILITY GROUP [AG1]   
MODIFY REPLICA ON  
N'sqlnode2' WITH   
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('sqlnode3','sqlnode1','sqlnode2')));  

ALTER AVAILABILITY GROUP [AG1]   
MODIFY REPLICA ON  
N'sqlnode3' WITH   
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('sqlnode2','sqlnode1','sqlnode3')));  

GO  
